/*
  # Add Designer Quote Generation System

  1. New Tables
    - `designer_quotes` - Store quotes generated by designers for customers
    - `quote_items` - Store individual line items in quotes

  2. Security
    - Enable RLS on all tables
    - Add policies for designers to manage their quotes
    - Add policies for customers to view quotes for their projects
*/

-- Create designer quotes table
CREATE TABLE IF NOT EXISTS designer_quotes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  designer_id uuid REFERENCES designers(id) ON DELETE CASCADE,
  project_id uuid REFERENCES customers(id) ON DELETE CASCADE,
  quote_number text NOT NULL,
  title text NOT NULL,
  description text,
  subtotal numeric(12,2) NOT NULL,
  discount_amount numeric(12,2) DEFAULT 0,
  tax_rate numeric(5,2) DEFAULT 18.0,
  tax_amount numeric(12,2) DEFAULT 0,
  total_amount numeric(12,2) NOT NULL,
  status text DEFAULT 'draft', -- 'draft', 'sent', 'accepted', 'rejected', 'expired'
  valid_until date,
  terms_and_conditions text,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create quote items table
CREATE TABLE IF NOT EXISTS quote_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_id uuid REFERENCES designer_quotes(id) ON DELETE CASCADE,
  material_id uuid REFERENCES designer_material_prices(id) ON DELETE SET NULL,
  item_type text NOT NULL, -- 'material', 'labor', 'service', 'other'
  name text NOT NULL,
  description text,
  quantity numeric(10,2) NOT NULL,
  unit text NOT NULL,
  unit_price numeric(10,2) NOT NULL,
  discount_percent numeric(5,2) DEFAULT 0,
  amount numeric(12,2) NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE designer_quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE quote_items ENABLE ROW LEVEL SECURITY;

-- Policies for designer_quotes
CREATE POLICY "Designers can manage their own quotes"
  ON designer_quotes
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM designers 
      WHERE designers.id = designer_quotes.designer_id 
      AND designers.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM designers 
      WHERE designers.id = designer_quotes.designer_id 
      AND designers.user_id = auth.uid()
    )
  );

CREATE POLICY "Customers can view quotes for their projects"
  ON designer_quotes
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM customers 
      WHERE customers.id = designer_quotes.project_id 
      AND customers.user_id = auth.uid()
    )
  );

-- Policies for quote_items
CREATE POLICY "Designers can manage their own quote items"
  ON quote_items
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM designer_quotes
      JOIN designers ON designers.id = designer_quotes.designer_id
      WHERE designer_quotes.id = quote_items.quote_id
      AND designers.user_id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM designer_quotes
      JOIN designers ON designers.id = designer_quotes.designer_id
      WHERE designer_quotes.id = quote_items.quote_id
      AND designers.user_id = auth.uid()
    )
  );

CREATE POLICY "Customers can view quote items for their projects"
  ON quote_items
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM designer_quotes
      JOIN customers ON customers.id = designer_quotes.project_id
      WHERE designer_quotes.id = quote_items.quote_id
      AND customers.user_id = auth.uid()
    )
  );

-- Trigger to automatically update updated_at
CREATE TRIGGER update_designer_quotes_updated_at
  BEFORE UPDATE ON designer_quotes
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_designer_quotes_designer_id 
ON designer_quotes(designer_id);

CREATE INDEX IF NOT EXISTS idx_designer_quotes_project_id 
ON designer_quotes(project_id);

CREATE INDEX IF NOT EXISTS idx_designer_quotes_status 
ON designer_quotes(status);

CREATE INDEX IF NOT EXISTS idx_quote_items_quote_id 
ON quote_items(quote_id);

CREATE INDEX IF NOT EXISTS idx_quote_items_material_id 
ON quote_items(material_id);